services:
  - type: web
    name: fgh-formulario
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn FichaMedica.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: FichaMedica.settings
      - key: SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: fichamedica
          property: connectionString
