# Generated by Django 5.2 on 2025-04-22 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ficha', '0002_paciente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'managed': True},
        ),
    ]
